image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Sync to GitHub (main)
          script:
            - chmod +x sync-to-github.sh
            - ./sync-to-github.sh
          services:
            - docker
            
    develop:
      - step:
          name: Sync to GitHub (develop)
          script:
            - chmod +x sync-to-github.sh
            - ./sync-to-github.sh
          services:
            - docker     
   
    qa:
      - step:
          name: Sync to GitHub (qa)
          script:
            - chmod +x sync-to-github.sh
            - ./sync-to-github.sh
          services:
            - docker
            
    pre-prod:
      - step:
          name: Sync to GitHub (pre-prod)
          script:
            - chmod +x sync-to-github.sh
            - ./sync-to-github.sh
          services:
            - docker 

definitions:
  services:
    docker:
      memory: 2048
